/*
* generated by Xtext
*/
package org.smadl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SMADLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.smadl.ui.internal.SMADLActivator.getInstance().getInjector("org.smadl.SMADL");
	}
	
}
