/*
* generated by Xtext
*/
package org.smadl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.smadl.services.SMADLGrammarAccess;

public class SMADLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SMADLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.smadl.parser.antlr.internal.InternalSMADLParser createParser(XtextTokenStream stream) {
		return new org.smadl.parser.antlr.internal.InternalSMADLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Entity";
	}
	
	public SMADLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SMADLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
