/*
 * generated by Xtext
 */
package org.smadl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SMADLUiModule extends org.smadl.ui.AbstractSMADLUiModule {
	public SMADLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
