/*
* generated by Xtext
*/
package org.smadl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SMADLStandaloneSetup extends SMADLStandaloneSetupGenerated{

	public static void doSetup() {
		new SMADLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

