/*
 * generated by Xtext
 */
package org.smadl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SMADLRuntimeModule extends org.smadl.AbstractSMADLRuntimeModule {

}
