/*
 * generated by Xtext
 */
package org.smadl.ui.contentassist

import org.smadl.ui.contentassist.AbstractSMADLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class SMADLProposalProvider extends AbstractSMADLProposalProvider {
}
